[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[functions]
  node_bundler = "esbuild"

# Environment variables for functions (these should be set in Netlify dashboard)
# VITE_SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY  
# STRIPE_SECRET_KEY
# URL

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Restrict resource loading
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://js.stripe.com https://checkout.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://api.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com;"
    
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Enable HSTS (force HTTPS)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Prevent XSS attacks
    X-XSS-Protection = "1; mode=block"
    
    # Control permissions
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(self)"

# Additional security for API endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    # Prevent caching of API responses
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    
    # Additional security for API
    X-Robots-Tag = "noindex, nofollow"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true