[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Redirect all Supabase Edge Function calls through Netlify function proxy
[[redirects]]
  from = "/functions/v1/*"
  to = "/.netlify/functions/supabase-proxy/:splat"
  status = 200
  force = true

# SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables template
[template.environment]
  VITE_SUPABASE_URL = "Your Supabase project URL"
  VITE_SUPABASE_ANON_KEY = "Your Supabase anonymous key"