[build]
  publish = "dist"
  command = "node build-check.js && npm ci && npm run build"

[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"
  # Increase Node memory limit for large builds
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Ensure dependencies are installed with exact versions
  NPM_FLAGS = "--production=false"

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Prevent MIME sniffing
    X-Content-Type-Options = "nosniff"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://unpkg.com https://cdn.jsdelivr.net; connect-src 'self' https://*.supabase.co https://api.stripe.com https://vendorhub-connect-portal.netlify.app; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-src https://js.stripe.com; object-src 'none'; base-uri 'self'; form-action 'self'"
    
    # Strict Transport Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Permissions Policy
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    
    # Cross-Origin policies
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-site"

# Redirect all Supabase Edge Function calls through Netlify function proxy
[[redirects]]
  from = "/functions/v1/*"
  to = "/.netlify/functions/supabase-proxy/:splat"
  status = 200
  force = true

# SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables template
[template.environment]
  VITE_SUPABASE_URL = "Your Supabase project URL"
  VITE_SUPABASE_ANON_KEY = "Your Supabase anonymous key"