name: E2E Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Set dummy env for Vite
        run: |
          echo "VITE_SUPABASE_URL=https://example.supabase.co" >> $GITHUB_ENV
          echo "VITE_SUPABASE_ANON_KEY=anon_key_placeholder_$(openssl rand -hex 16)" >> $GITHUB_ENV

      - name: Start Vite dev server
        run: |
          npm run dev &> dev-server.log &
          for i in {1..90}; do
            if curl -sSf http://localhost:8080 > /dev/null; then
              echo "Dev server is up";
              break;
            fi
            sleep 1
          done
          if ! curl -sSf http://localhost:8080 > /dev/null; then
            echo "Dev server failed to start"; tail -n +1 dev-server.log; exit 1;
          fi

      - name: Run Playwright smoke test
        run: npm run test:e2e

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore

      - name: Upload dev server log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dev-server-log
          path: dev-server.log
          if-no-files-found: ignore